### ISSUE TITLE
Tweakchutes

### ISSUE THREAD

**Issue by DanShu15** [Sigma88/Sigma-TweakChutes#2]
Issue:
"@name = TweakChute" appears to break compatibility with SafeChute and Stage Recovery.
Sorry to contact you through the forums first, I just noticed that you prefer Github right after I sent the PM :)

**Comment by Sigma88** [comment]
no problem, pinging me on the forum is fine, you just risk not getting a reply in a timely manner because I sometimes forget to check the forum

I'm working on a solution, I think I might have found one already

**Comment by Sigma88** [comment]
could you give this a try?
[SigmaTweakChutes.v0.3.0.ALPHA.zip](https://github.com/Sigma88/Sigma-TweakChutes/files/3275818/SigmaTweakChutes.v0.3.0.ALPHA.zip)

delete the old plugin from JNSQ and replace it with the one in the zip archive
(it doesn't matter if they have different names)

you should also find the cfg that JNSQ uses to replace the parachutes and change it to this:

```
@PART:FINAL
{
    +MODULE[ModuleParachute]:HAS[#minAirPressureToOpen[0.04]]
    {
        @name = TweakChute
        altitudeSliderMin = 50
        altitudeSliderMax = 5000
        altitudeSliderStep = 50
        pressureSliderMin = 0.04
        pressureSliderMax = 0.75
        pressureSliderStep = 0.01
    }
    +MODULE[ModuleParachute]:HAS[#minAirPressureToOpen[0.02]]
    {
        @name = TweakChute
        altitudeSliderMin = 50
        altitudeSliderMax = 5000
        altitudeSliderStep = 50
        pressureSliderMin = 0.02
        pressureSliderMax = 0.75
        pressureSliderStep = 0.01
    }
}
```

**Comment by DanShu15** [comment]
looks great!
Would you mind tossing me a link when you publish them? I'd like to send people using my mod collection for the livestream over to grab the fixes before the next update since Scatterer is being a little tricky and it'll be holding up the next JNSQ release with these included.
Thanks a ton! great idea too, adding a key for the plugin to target but not changing what the other mods are going for :) great job!

**Comment by Sigma88** [comment]
I released the new version, you can find it here:
https://github.com/Sigma88/Sigma-TweakChutes/releases/latest

remember that the files from JNSQ have to be replaced/edited in order for the plugin to work correctly
so you might want to prepare an archive with the modified cfg files as well

if you decide to make a downloadable archive for your followers you have my permission to include the version 0.3.0 of my plugin in that archive

**Comment by DanShu15** [comment]
Sweet!
That'll be handy since we've got some personal taste balance patches and a remote tech patch already done that won't be with JNSQ til next update.
I sure appreciate the help ☺



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Sigma88** [comment]
When are you going to stream next?

I'd like to come check out how the chutes behave

**Comment by DanShu15** [comment]
Today's the end of my weekend, I'll be on in the mornings til next Sunday ☺ twitch.tv/DanShuTV



Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------
